<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [14]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [2]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('OSLO_EXPANDIDO.csv')
data.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,42932,https://www.airbnb.com/rooms/42932,20260630053456,2026-07-02,previous scrape,"Charming apartment, Oslo Center, Ro",NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,187463,...,4.96,4.96,4.86,NaN,NaN,2,2,0,0,0.35
1,71725,https://www.airbnb.com/rooms/71725,20260630053456,2026-06-30,city scrape,Central big room - ap with balcony,A bargain in Oslo!!<br />Room in new and fully...,NaN,https://a0.muscache.com/pictures/468893/9c8190...,368229,...,4.95,4.74,4.82,NaN,NaN,1,0,1,0,0.33
2,149776,https://www.airbnb.com/rooms/149776,20260630053456,2026-06-30,city scrape,Bird's nest in the heart of Oslo,"A double room in a spacious, elegant apartment...",NaN,https://a0.muscache.com/pictures/fc1eb1a5-0ab8...,714768,...,4.96,4.89,4.85,NaN,NaN,2,0,2,0,0.27
3,165218,https://www.airbnb.com/rooms/165218,20260630053456,2026-06-30,city scrape,"Bedroom, nice riverview, in Oslo",NaN,NaN,https://a0.muscache.com/pictures/1095417/f64e2...,787976,...,4.84,4.74,4.81,NaN,NaN,1,0,1,0,0.18
4,174372,https://www.airbnb.com/rooms/174372,20260630053456,2026-07-02,previous scrape,New spacious central 2BR w/terrace,NaN,NaN,https://a0.muscache.com/pictures/2267871/8fd04...,114189,...,4.88,4.79,4.88,NaN,NaN,2,2,0,0,0.19

In [ ]:
#Extraer las 50 columnas más relevantes para hacer análisis de datos 

#Vemos con que información cuenta la base de datos 
print(list(data.columns))

['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months', 'hosts_time_as_host_years', 'hosts_time_as_host_months', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'price_quote_checkin_date', 'price_quote_checkout_date', 'price_quote_total_price', 'price_quote_price_per_night', 'price_quote_raw', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month']

In [ ]:
#Vamos a reducir las columnas usando los siguientes criterios:
#Enlaces (no aportan para usos estadísticos), descripciones (usan formato str)
#Datos redundantes (mucha información sobre el mismo tema), por lo tanto tenemos lo siguiente:

columnas_50 = [
    # Identificación y ubicación
    "id",
    "host_id",
    "neighbourhood",
    "neighbourhood_cleansed",
    "neighbourhood_group_cleansed",
    "latitude",
    "longitude",
    "host_location",
    # Anfitrión
    "host_name",
    "host_since",
    "hosts_time_as_host_years",
    "host_response_time",
    "host_response_rate",
    "host_acceptance_rate",
    "host_is_superhost",
    "host_listings_count",
    "host_total_listings_count",
    "host_identity_verified",
    "calculated_host_listings_count",
    # Propiedad
    "property_type",
    "room_type",
    "accommodates",
    "bathrooms",
    "bathrooms_text",
    "bedrooms",
    "beds",
    "amenities",
    "instant_bookable",
    "license",
    # Precios
    "price",
    "price_quote_price_per_night",
    "price_quote_total_price",
    "estimated_revenue_l365d",
    "estimated_occupancy_l365d",
    "has_availability",
    # Disponibilidad
    "minimum_nights",
    "maximum_nights",
    "minimum_nights_avg_ntm",
    "maximum_nights_avg_ntm",
    "availability_30",
    "availability_60",
    "availability_90",
    "availability_365",
    # Reseñas
    "number_of_reviews",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "reviews_per_month",
    "review_scores_rating",
    "review_scores_location",
    "review_scores_value",
]

# Data frame nuevo
df_50 = data[columnas_50]

# Nuevo CSV 
df_50.to_csv("OSLO_50_columnas.csv", index=False)

In [4]:
#Carga desde un archivo .csv sin indice
data2 = pd.read_csv('OSLO_50_columnas.csv')
data2.head(5)

,id,host_id,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,host_location,host_name,host_since,...,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,reviews_per_month,review_scores_rating,review_scores_location,review_scores_value
0,42932,187463,NaN,Frogner,NaN,59.91201,10.72455,"Oslo, Norway",Cecilie,NaN,...,0,0,0,55,1,0,0.35,4.91,4.96,4.86
1,71725,368229,NaN,Gamle Oslo,NaN,59.90795,10.77987,"Oslo, Norway",Reidun,NaN,...,12,16,182,62,5,0,0.33,4.78,4.74,4.82
2,149776,714768,NaN,St. Hanshaugen,NaN,59.92398,10.74787,"Oslo, Norway",Henrik,NaN,...,60,90,365,49,4,1,0.27,4.92,4.89,4.85
3,165218,787976,NaN,Sagene,NaN,59.93750,10.76554,"Oslo, Norway",Jon,NaN,...,26,30,41,32,3,0,0.18,4.88,4.74,4.81
4,174372,114189,NaN,Sagene,NaN,59.93024,10.75964,"Oslo, Norway",Christina,NaN,...,60,90,365,35,0,0,0.19,4.87,4.79,4.88

In [5]:
#Identificar valores nulos por columna
valores_nulos = data2.isnull().sum()
valores_nulos

id                                    0
host_id                               0
neighbourhood                     13391
neighbourhood_cleansed                0
neighbourhood_group_cleansed      13391
latitude                              0
longitude                             0
host_location                      2564
host_name                             0
host_since                        13391
hosts_time_as_host_years              1
host_response_time                13391
host_response_rate                13391
host_acceptance_rate              13391
host_is_superhost                     0
host_listings_count                   0
host_total_listings_count         13391
host_identity_verified                0
calculated_host_listings_count        0
property_type                         0
room_type                             0
accommodates                          0
bathrooms                          4353
bathrooms_text                        6
bedrooms                           1490
beds                               4022
amenities                             0
instant_bookable                  13391
license                           13391
price                              3550
price_quote_price_per_night        3550
price_quote_total_price            3550
estimated_revenue_l365d            3550
estimated_occupancy_l365d             0
has_availability                    248
minimum_nights                        1
maximum_nights                        1
minimum_nights_avg_ntm                0
maximum_nights_avg_ntm                0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
number_of_reviews                     0
number_of_reviews_ltm                 0
number_of_reviews_l30d                0
reviews_per_month                  2808
review_scores_rating               2808
review_scores_location             2808
review_scores_value                2809
dtype: int64

**Métodos de Sustitución de Valores Nulos**

Aplicación de métodos para reemplazar valores nulos, justificando la razón de acuerdo a la variable

In [ ]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
#Usamos el valor promedio de la ciudad para darle un número de baños lógico y equilibrado a las viviendas sin datos.
data2["bathrooms"] = data2["bathrooms"].fillna(round(data2["bathrooms"].mean(), 1))

In [9]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                    0
host_id                               0
neighbourhood                     13391
neighbourhood_cleansed                0
neighbourhood_group_cleansed      13391
latitude                              0
longitude                             0
host_location                      2564
host_name                             0
host_since                        13391
hosts_time_as_host_years              1
host_response_time                13391
host_response_rate                13391
host_acceptance_rate              13391
host_is_superhost                     0
host_listings_count                   0
host_total_listings_count         13391
host_identity_verified                0
calculated_host_listings_count        0
property_type                         0
room_type                             0
accommodates                          0
bathrooms                             0
bathrooms_text                        6
bedrooms                           1490
beds                               4022
amenities                             0
instant_bookable                  13391
license                           13391
price                              3550
price_quote_price_per_night        3550
price_quote_total_price            3550
estimated_revenue_l365d            3550
estimated_occupancy_l365d             0
has_availability                    248
minimum_nights                        1
maximum_nights                        1
minimum_nights_avg_ntm                0
maximum_nights_avg_ntm                0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
number_of_reviews                     0
number_of_reviews_ltm                 0
number_of_reviews_l30d                0
reviews_per_month                  2808
review_scores_rating               2808
review_scores_location             2808
review_scores_value                2809
dtype: int64

In [11]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
#Usamos la mediana dado que evita que los valores extremadamente altos o bajos distorsionen la información.
data2["bedrooms"]=data2["bedrooms"].fillna(round(data2["bedrooms"].median(),1))
data2["hosts_time_as_host_years"]=data2["hosts_time_as_host_years"].fillna(round(data2["hosts_time_as_host_years"].median(),1))
data2["minimum_nights"]=data2["minimum_nights"].fillna(round(data2["minimum_nights"].median(),1))
data2["maximum_nights"]=data2["maximum_nights"].fillna(round(data2["maximum_nights"].median(),1))
data2["review_scores_rating"]=data2["review_scores_rating"].fillna(round(data2["review_scores_rating"].median(),1))
data2["review_scores_location"]=data2["review_scores_location"].fillna(round(data2["review_scores_location"].median(),1))
data2["review_scores_value"]=data2["review_scores_value"].fillna(round(data2["review_scores_value"].median(),1))

In [13]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                    0
host_id                               0
neighbourhood                     13391
neighbourhood_cleansed                0
neighbourhood_group_cleansed      13391
latitude                              0
longitude                             0
host_location                      2564
host_name                             0
host_since                        13391
hosts_time_as_host_years              0
host_response_time                13391
host_response_rate                13391
host_acceptance_rate              13391
host_is_superhost                     0
host_listings_count                   0
host_total_listings_count         13391
host_identity_verified                0
calculated_host_listings_count        0
property_type                         0
room_type                             0
accommodates                          0
bathrooms                             0
bathrooms_text                        6
bedrooms                              0
beds                               4022
amenities                             0
instant_bookable                  13391
license                           13391
price                              3550
price_quote_price_per_night        3550
price_quote_total_price            3550
estimated_revenue_l365d            3550
estimated_occupancy_l365d             0
has_availability                    248
minimum_nights                        0
maximum_nights                        0
minimum_nights_avg_ntm                0
maximum_nights_avg_ntm                0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
number_of_reviews                     0
number_of_reviews_ltm                 0
number_of_reviews_l30d                0
reviews_per_month                  2808
review_scores_rating                  0
review_scores_location                0
review_scores_value                   0
dtype: int64

In [16]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
#Usamos constantes lógicas de acuerda a la variable
data2["host_since"]= data2["host_since"].fillna(2026) 
data2["host_total_listings_count"] = data2["host_total_listings_count"].fillna(0)
data2["reviews_per_month"] = data2["reviews_per_month"].fillna(0)

In [18]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                    0
host_id                               0
neighbourhood                     13391
neighbourhood_cleansed                0
neighbourhood_group_cleansed      13391
latitude                              0
longitude                             0
host_location                      2564
host_name                             0
host_since                            0
hosts_time_as_host_years              0
host_response_time                13391
host_response_rate                13391
host_acceptance_rate              13391
host_is_superhost                     0
host_listings_count                   0
host_total_listings_count             0
host_identity_verified                0
calculated_host_listings_count        0
property_type                         0
room_type                             0
accommodates                          0
bathrooms                             0
bathrooms_text                        6
bedrooms                              0
beds                               4022
amenities                             0
instant_bookable                  13391
license                           13391
price                              3550
price_quote_price_per_night        3550
price_quote_total_price            3550
estimated_revenue_l365d            3550
estimated_occupancy_l365d             0
has_availability                    248
minimum_nights                        0
maximum_nights                        0
minimum_nights_avg_ntm                0
maximum_nights_avg_ntm                0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
number_of_reviews                     0
number_of_reviews_ltm                 0
number_of_reviews_l30d                0
reviews_per_month                     0
review_scores_rating                  0
review_scores_location                0
review_scores_value                   0
dtype: int64

In [29]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
#A las columnas de texto vacías les pusimos una etiqueta clara para saber que la información 
#no venía en la base de datos y no dejar la celda en blanco.

data2["neighbourhood"] =data2["neighbourhood"].fillna("Sin Información") 
data2["neighbourhood_group_cleansed"] =data2["neighbourhood_group_cleansed"].fillna("Sin Información") 
data2["host_location"] =data2["host_location"].fillna("Sin Información") 
data2["host_response_rate"] =data2["host_response_rate"].fillna("Sin Información") 
data2["host_acceptance_rate"] =data2["host_acceptance_rate"].fillna("Sin Información") 
data2["bathrooms_text"] =data2["bathrooms_text"].fillna("Sin Información") 
data2["instant_bookable"] =data2["instant_bookable"].fillna("Sin Información") 
data2["license"] =data2["license"].fillna("Sin Información") 
data2["has_availability"] =data2["has_availability"].fillna("Sin Información") 
data2["host_response_time"] =data2["host_response_time"].fillna("Sin Información")

In [30]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                0
host_id                           0
neighbourhood                     0
neighbourhood_cleansed            0
neighbourhood_group_cleansed      0
latitude                          0
longitude                         0
host_location                     0
host_name                         0
host_since                        0
hosts_time_as_host_years          0
host_response_time                0
host_response_rate                0
host_acceptance_rate              0
host_is_superhost                 0
host_listings_count               0
host_total_listings_count         0
host_identity_verified            0
calculated_host_listings_count    0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bathrooms_text                    0
bedrooms                          0
beds                              1
amenities                         0
instant_bookable                  0
license                           0
price                             0
price_quote_price_per_night       0
price_quote_total_price           0
estimated_revenue_l365d           0
estimated_occupancy_l365d         0
has_availability                  0
minimum_nights                    0
maximum_nights                    0
minimum_nights_avg_ntm            0
maximum_nights_avg_ntm            0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
reviews_per_month                 0
review_scores_rating              0
review_scores_location            0
review_scores_value               0
dtype: int64

In [23]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
data2["beds"] =data2["beds"].ffill()

In [31]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                0
host_id                           0
neighbourhood                     0
neighbourhood_cleansed            0
neighbourhood_group_cleansed      0
latitude                          0
longitude                         0
host_location                     0
host_name                         0
host_since                        0
hosts_time_as_host_years          0
host_response_time                0
host_response_rate                0
host_acceptance_rate              0
host_is_superhost                 0
host_listings_count               0
host_total_listings_count         0
host_identity_verified            0
calculated_host_listings_count    0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bathrooms_text                    0
bedrooms                          0
beds                              1
amenities                         0
instant_bookable                  0
license                           0
price                             0
price_quote_price_per_night       0
price_quote_total_price           0
estimated_revenue_l365d           0
estimated_occupancy_l365d         0
has_availability                  0
minimum_nights                    0
maximum_nights                    0
minimum_nights_avg_ntm            0
maximum_nights_avg_ntm            0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
reviews_per_month                 0
review_scores_rating              0
review_scores_location            0
review_scores_value               0
dtype: int64

In [26]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
#Rellenamos los precios faltantes tomando el costo de la propiedad siguiente como referencia de mercado.

data2["price"] =data2["price"].bfill() 
data2["price_quote_price_per_night"] =data2["price_quote_price_per_night"].bfill() 
data2["price_quote_total_price"] =data2["price_quote_total_price"].bfill() 
data2["estimated_revenue_l365d"] =data2["estimated_revenue_l365d"].bfill()

In [32]:
#Corroboramos valores nulos
valores_nulos=data2.isnull().sum()
valores_nulos

id                                0
host_id                           0
neighbourhood                     0
neighbourhood_cleansed            0
neighbourhood_group_cleansed      0
latitude                          0
longitude                         0
host_location                     0
host_name                         0
host_since                        0
hosts_time_as_host_years          0
host_response_time                0
host_response_rate                0
host_acceptance_rate              0
host_is_superhost                 0
host_listings_count               0
host_total_listings_count         0
host_identity_verified            0
calculated_host_listings_count    0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bathrooms_text                    0
bedrooms                          0
beds                              1
amenities                         0
instant_bookable                  0
license                           0
price                             0
price_quote_price_per_night       0
price_quote_total_price           0
estimated_revenue_l365d           0
estimated_occupancy_l365d         0
has_availability                  0
minimum_nights                    0
maximum_nights                    0
minimum_nights_avg_ntm            0
maximum_nights_avg_ntm            0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
reviews_per_month                 0
review_scores_rating              0
review_scores_location            0
review_scores_value               0
dtype: int64

In [34]:
data2.to_csv("OSLO_50_COLUMNAS_LIMPIO.csv", index=False)